# Generated by Django 2.0.5 on 2020-06-18 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=200, null=True)),
                ('sensor_name', models.CharField(max_length=200, null=True)),
                ('sensor_unit', models.CharField(max_length=200, null=True)),
                ('min_range', models.CharField(max_length=200, null=True)),
                ('max_range', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AddSensor',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=40, null=True)),
                ('wd_sensor_name', models.CharField(max_length=100, null=True)),
                ('wd_unit', models.CharField(max_length=10, null=True)),
                ('ws_sensor_name', models.CharField(max_length=15, null=True)),
                ('ws_unit', models.CharField(max_length=10, null=True)),
                ('rg_sensor_name', models.CharField(max_length=100, null=True)),
                ('rg_unit', models.CharField(max_length=10, null=True)),
                ('pm2_5_sensor_name', models.CharField(max_length=100, null=True)),
                ('pm2_5_unit', models.CharField(max_length=10, null=True)),
                ('pm10_sensor_name', models.CharField(max_length=100, null=True)),
                ('pm10_unit', models.CharField(max_length=10, null=True)),
                ('humidity_sensor_name', models.CharField(max_length=100, null=True)),
                ('humidity_unit', models.CharField(max_length=10, null=True)),
                ('temperature_sensor_name', models.CharField(max_length=100, null=True)),
                ('temperature_unit', models.CharField(max_length=10, null=True)),
                ('so2_sensor_name', models.CharField(max_length=100, null=True)),
                ('so2_unit', models.CharField(max_length=10, null=True)),
                ('co_sensor_name', models.CharField(max_length=100, null=True)),
                ('co_unit', models.CharField(max_length=10, null=True)),
                ('no2_sensor_name', models.CharField(max_length=100, null=True)),
                ('no2_unit', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('modified_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='Weather_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.IntegerField(null=True)),
                ('rain_gauge', models.CharField(max_length=200, null=True)),
                ('pm2_5', models.CharField(max_length=200, null=True)),
                ('pm10', models.CharField(max_length=200, null=True)),
                ('humidity', models.CharField(max_length=200, null=True)),
                ('temperature', models.CharField(max_length=200, null=True)),
                ('ws_value', models.CharField(max_length=200, null=True)),
                ('wd_value', models.CharField(max_length=200, null=True)),
                ('no2', models.CharField(max_length=200, null=True)),
                ('co', models.CharField(max_length=200, null=True)),
                ('so2', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Weather_data',
            },
        ),
    ]
